### ISSUE TITLE
throw error npm start:prod

### ISSUE THREAD

**Issue by buzzbo** [wiseindy/timer-for-google-assistant#3]
I get an error when I run npm `npm run strart:prod`
```
$ npm run start:prod`

> timer-for-google-assistant@0.1.0 start:prod /home/pi/git/timer-for-google-assistant
> node dist/main

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/pi/git/timer-for-google-assistant/dist/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! timer-for-google-assistant@0.1.0 start:prod: `node dist/main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the timer-for-google-assistant@0.1.0 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-30T03_08_40_304Z-debug.log
```

**Comment by wiseindy** [comment]
Run `npm run build` once before running `npm run start:prod`

**Comment by buzzbo** [comment]
OK thank you!
